<template>
  <div class="proyectos">
    <Header :title="''" :subtitle="'Proyectos'" />
    <b-row>
      <b-colxx xxs="12">
        <!-- <piaf-breadcrumb :heading="$t('menu.analytics')" /> -->
        <div class="cont-btn-newProyect">
          <button class="btn btn-newProyect">Nuevo Proyecto</button>
        </div>

        <DataAndalucia 
          :id="'DataAndalucia'"
          :title="'Andalucía_copy'"
          :subtitle="'Teaser name: Ginebra'"
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Brownfield - Financiación (Solar)'"
          :data4= "'4 Plantas - 4 MW'"
          :data5= "'Energía Aljaval'"
          :data6= "'Santiago Molina'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseWhite'"
          :ProductModalDisplay="'block'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'block'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'block'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'contents'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />

        <DataAndalucia 
          :id="'DataProspectA5FaseN9'"
          :title="'Prospect A5 Nº 9'"
          :subtitle="'' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Financiación (Solar)'"
          :data4= "'6 MW'"
          :data5= "'Souto Solar'"
          :data6= "'Guillermo Souto'"
          :fase= "'Fase 0'"
          :faseClass="'faseBlue'"
          :descripFase="'Prospecto'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'none'"
          :A5psModalClass="'faseRed'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'none'"
          :ProductModalClass="'faseWhite'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />

        <DataAndalucia 
          :id="'DataProspectA5FaseN6'"
          :title="'Prospect A5 Nº 6'"
          :subtitle="'' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Financiación (Solar)'"
          :data4= "'4 MW'"
          :data5= "'Souto Solar'"
          :data6= "'Santiago Molina'"
          :fase= "'Fase 0'"
          :faseClass="'faseRed'"
          :descripFase="'Registrado en la Plataforma'"
          :RfasModalClass="'faseBlue'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseRed'"
          :A5psModalDisplay="'none'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'none'"
          :ProductModalClass="'faseWhite'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />

        <DataAndalucia 
          :id="'Andalucía_copy2'"
          :title="'Andalucía_copy'"
          :subtitle="'Teaser name: Andalucia prueba' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Brownfield - Financiación (Solar)'"
          :data4= "'1 Plantas - 133 MW'"
          :data5= "'Energía Aljaval'"
          :data6= "'Santiago Molina'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseWhite'"
          :ProductModalDisplay="'block'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />

        <DataAndalucia 
          :id="'GranFregacedos_copy'"
          :title="'Gran Fregacedos_copy'"
          :subtitle="'Teaser name: Ginebra' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Venta (Solar)'"
          :data4= "'1 Plantas - 133 MW'"
          :data5= "'Fotones Energy & Water'"
          :data6= "'Guillermo Souto'"
          :fase= "'Fase II'"
          :faseClass="'faseWarning'"
          :descripFase="'En Revisión'"
          :RfasModalClass="'faseWarning'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'none'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'none'"
          :ProductModalClass="'faseWhite'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />
        
        <DataAndalucia 
          :id="'Andalucía'"
          :title="'Andalucía'"
          :subtitle="'Teaser name: Mérida' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Brownfield - Financiación (Solar)'"
          :data4= "'4 Plantas - 4 MW'"
          :data5= "'Energía Aljaval'"
          :data6= "'Salvador Carrillo Bardo'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso'"
          :RfasModalClass="'faseGreen'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseGreen'"
          :ProductModalDisplay="'block'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'none'"
        />

        <DataAndalucia 
          :id="'Cairo1'"
          :title="'Cairo'"
          :subtitle="'Teaser name: Cairo' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Financiación (Solar)'"
          :data4= "'1 Plantas - 450 MW'"
          :data5= "'Grupo Fotones'"
          :data6= "'Guillermo Souto'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseWhite'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseGreen'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />

        <DataAndalucia 
          :id="'SesVinyes'"
          :title="'Ses Vinyes'"
          :subtitle="'Teaser name: Ses Vinyes' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Brownfield - Financiación (Eólico)'"
          :data4= "'1 Plantas - 4 MW'"
          :data5= "'Energía Aljaval'"
          :data6= "'Guillermo Souto'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseWhite'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseGreen'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />

        <DataAndalucia 
          :id="'Merida2'"
          :title="'Mérida'"
          :subtitle="'Teaser name: Andalucía' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Brownfield - Financiación (Eólico)'"
          :data4= "'1 Plantas - 4 MW'"
          :data5= "'Energía Aljaval'"
          :data6= "'Guillermo Souto'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseWhite'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseGreen'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />
        <DataAndalucia 
          :id="'Torito'"
          :title="'Torito'"
          :subtitle="'Teaser name: Toro Bravo' "
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Financiación (Solar)'"
          :data4= "'1 Plantas - 4 MW'"
          :data5= "'Toro Solar'"
          :data6= "'Miguel Solana'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseWhite'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseGreen'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />
        <DataAndalucia 
          :id="'sdc'"
          :title="'sdc'"
          :subtitle="''"
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Financiación (Solar)'"
          :data4= "'1 Plantas - 4 MW'"
          :data5= "'acwc'"
          :data6= "'Miguel Solana'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso - Sin RFA'"
          :RfasModalClass="'faseWhite'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseWhite'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseGreen'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />
        <DataAndalucia 
          :id="'Petra'"
          :title="'Petra'"
          :subtitle="'Teaser name: Petra'"
          :data1= "'Senior Bridge GEB: EUR 24,4 M'"
          :data2= "'Asset Acquisition: EUR 60,2 M'"
          :data3= "'Greenfield - Financiación (Solar)'"
          :data4= "'9 Plantas - 396.5 MW'"
          :data5= "'IPC'"
          :data6= "'Manager'"
          :fase= "'Fase II'"
          :faseClass="'faseBlue'"
          :descripFase="'Data Room en proceso'"
          :RfasModalClass="'faseGreen'"
          :RfasModalDisplay="'block'"
          :A5psModalClass="'faseGreen'"
          :A5psModalDisplay="'block'"
          :DocumentationModalClass="'faseGreen'"
          :DocumentationModalDisplay="'block'"
          :ProductModalClass="'faseWhite'"
          :ProductModalDisplay="'none'"
          :ProductManagentModalClass="'faseWhite'"
          :ProductManagentModalDisplay="'none'"
          :ReviewModalClass="'faseRed'"
          :ReviewModalDisplay="'none'"
          :MarketPlaceModalClass="'faseGreen'"
          :MarketPlaceModalDisplay="'none'"
          :MarketPlaceModalNODATAClass="'faseWhite'"
          :MarketPlaceModalNODATADisplay="'contents'"
        />


        <vuetable-pagination-bootstrap
          class="mt-4"
          ref="pagination"
        />
      </b-colxx>
    </b-row>

  </div>
</template>

<script>
import Header from "../../../components/Headers/HeaderProyecto";
import DataAndalucia from "../../../components/Cards/DataAndalucia";
import VuetablePaginationBootstrap from "../../../components/Common/VuetablePaginationBootstrap";




export default {
  data() {
    return {
      styleobj: {
        backgroundColor:"red"
      }
    }
  },
  components: {
    "Header": Header,
    "DataAndalucia": DataAndalucia,
    "vuetable-pagination-bootstrap": VuetablePaginationBootstrap,
  },


};
</script>
